name: Update Snake SVG
on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza diariamente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate SVG
        run: |
          SVG='<svg xmlns="http://www.w3.org/2000/svg" width="400" height="60">
                <rect width="100%" height="100%" fill="#0D1117"/>
                <text x="50%" y="50%" font-family="monospace" font-size="14" fill="#58A6FF" text-anchor="middle">
                  🐍 Snake Game | Atualizado em: $(date +%d/%m/%Y)
                </text>
              </svg>'
          echo "$SVG" > snake.svg
      - name: Update README
        uses: EndBug/add-and-commit@v9
        with:
          add: snake.svg
          message: "Update SVG"
